layout_spectrum: 0.20517874648794532
typography_spectrum: 0.4217559192329645
color:
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  brandStrength: 0.26177073922008276
  lightness: 0.7304475845303386
  saturation: 0.8733447517734021
  rhythmicContrast: 0.4633072924334556
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f331a65-d13b-4600-bf3e-6498fbd9645a.jpg
  type: www.facebook.com/corporatemetalsolutions
  appId: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
author:
  name: Contact Web Designer
  email: jeffrey@corporatemetalsolutions.com
  url: www.corporatemetalsolutions.com
name: Corporate Metal Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Jewelry, Accessories, & everything Metal'
description: SAGE 68135 ASI 51918
purpose: []
