name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.75361
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a6a39a'
    - '#1e3c72'
    - '#566262'
    - '#141510'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
