name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.9991
typography_spectrum: 0.49188
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a4a4a4'
    - '#737373'
    - '#323230'
    - '#fffd9d'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
