layout_spectrum: 0.222674178192392
typography_spectrum: 0.7689479414839298
color:
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  brandStrength: 0.26177073922008276
  lightness: 0.7304475845303386
  saturation: 0.8733447517734021
  rhythmicContrast: 0.4633072924334556
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f331a65-d13b-4600-bf3e-6498fbd9645a.jpg
  type: www.facebook.com/corporatemetalsolutions
  appId: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
author:
  name: Contact Web Designer
  email: jeffrey@corporatemetalsolutions.com
  url: www.corporatemetalsolutions.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f05d162-950c-4825-8c22-6c20d874b410.jpg
name: Corporate Metal Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6abc93b5-3df8-4f01-9f14-55bbe282a219.jpg
title: 'Jewelry, Accessories, & everything Metal'
description: SAGE 68135 ASI 51918
purpose: []
