name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.74819
typography_spectrum: 0.75361
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a39da1'
    - '#e0d2cf'
    - '#4a2b0e'
    - '#fefea6'
    - '#8c5c1e'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
