name: eLine Jewelers
favicon: null
layout_spectrum: 0.31137
typography_spectrum: 1
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69988233-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b59759'
    - '#d5c29d'
    - '#ebe2cc'
    - '#c5b184'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
