analytics:
  google: UA-69988233-1
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 0.375
  lightness: 0.5
  rhythmicContrast: 0.25
  saturation: 0.125
cta: {}
layout_spectrum: 0.24639
name: eLine Jewelers
opengraph: {}
purpose: []
typography_spectrum: 1
