layout_spectrum: 0.5160817145369947
typography_spectrum: 0.7962143002077937
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6931276710238308
  lightness: 0.08672962407581508
  saturation: 0.674743268173188
  rhythmicContrast: 0.3767966649029404
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f331a65-d13b-4600-bf3e-6498fbd9645a.jpg
  type: www.facebook.com/corporatemetalsolutions
  appId: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
author:
  name: Contact Web Designer
  email: jeffrey@corporatemetalsolutions.com
  url: www.corporatemetalsolutions.com
name: Corporate Metal Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Jewelry, Accessories, & everything Metal'
description: SAGE 68135 ASI 51918
purpose: []
