layout_spectrum: 0.1449380146805197
typography_spectrum: 0.2867695742752403
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.29423590982332826
  lightness: 0.14008665177971125
  saturation: 0.6455345200374722
  rhythmicContrast: 0.819510460132733
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
name: Corporate Metal Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Corporate Jewelry and Custom Awards
description: Everything Metal!
purpose: []
