name: eLine Jewelers
favicon: null
layout_spectrum: 0.92932
typography_spectrum: 1
title: e-Line Jewellers Corporate Jewelry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69988233-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9d998d'
    - '#376597'
    - '#4e8ad0'
    - '#5d5a53'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
