name: eLine Jewelers
favicon: null
layout_spectrum: 0.94675
typography_spectrum: 1
title: e-Line Jewellers Corporate Jewelry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69988233-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b4965a'
    - '#353535'
    - '#d0d0d0'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
