analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b7995b'
    - '#3e3e3e'
    - '#b7b7b7'
  brandStrength: 0.8125
  lightness: 0.25
  rhythmicContrast: 0.25
  saturation: 0
cta: {}
layout_spectrum: 0.67943
name: eLine Jewelers
opengraph: {}
purpose: []
typography_spectrum: 1
