name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.88008
typography_spectrum: 0.49188
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b59759'
    - '#d5c29d'
    - '#ebe2cc'
    - '#c5b184'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
