name: eLine Jewelers
favicon: null
layout_spectrum: 0.49549
typography_spectrum: 1
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69988233-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cccccc'
    - '#5f5f5f'
    - '#bbbbbb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
