layout_spectrum: 0.41482579335570335
typography_spectrum: 0.4608098247554153
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.34120760299265385
  lightness: 0.9949174684006721
  saturation: 0.2051346532534808
  rhythmicContrast: 0.6576566810254008
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f331a65-d13b-4600-bf3e-6498fbd9645a.jpg
  type: www.facebook.com/corporatemetalsolutions
  appId: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
author:
  name: Contact Web Designer
  email: jeffrey@corporatemetalsolutions.com
  url: www.corporatemetalsolutions.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f05d162-950c-4825-8c22-6c20d874b410.jpg
name: Corporate Metal Solutions
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6abc93b5-3df8-4f01-9f14-55bbe282a219.jpg
title: 'Jewelry, Accessories, & everything Metal'
description: SAGE 68135 ASI 51918
purpose: []
