name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.75903
typography_spectrum: 0.50632
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b4965a'
    - '#bababa'
    - '#5d5d5d'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
