name: Corporate Metal Solutions
favicon: null
layout_spectrum: 0.26444
typography_spectrum: 0.50632
title: Corporate Jewelry and Custom Awards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73744525-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#1c1c1c'
    - '#898579'
    - '#b4b4b4'
    - '#585449'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
